# permissions for end users to edit children.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: child-editor-role
rules:
- apiGroups:
  - test.kkohtaka.org
  resources:
  - children
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.kkohtaka.org
  resources:
  - children/status
  verbs:
  - get
