# permissions for end users to view children.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: child-viewer-role
rules:
- apiGroups:
  - test.kkohtaka.org
  resources:
  - children
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.kkohtaka.org
  resources:
  - children/status
  verbs:
  - get
