# permissions for end users to edit parents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parent-editor-role
rules:
- apiGroups:
  - test.kkohtaka.org
  resources:
  - parents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.kkohtaka.org
  resources:
  - parents/status
  verbs:
  - get
