# permissions for end users to view parents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parent-viewer-role
rules:
- apiGroups:
  - test.kkohtaka.org
  resources:
  - parents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.kkohtaka.org
  resources:
  - parents/status
  verbs:
  - get
